name: Deploy Production

# on:
#   push:
#     branches: ["master"]

on:
  release:
    types: [released]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          username: ${{ secrets.SERVER_USER }}
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 60m 
          script: |
            cd ~/kraicklist || exit 0

            echo "Pulling latest code..."
            git pull origin master

            export PORT=${{ secrets.PORT }}
            export SEARCH_ENGINE_API_URL=${{ secrets.SEARCH_ENGINE_API_URL }}
            export SEARCH_ENGINE_API_KEY=${{ secrets.SEARCH_ENGINE_API_KEY }}
            export SEARCH_ENGINE_COLLECTION_NAME=${{ secrets.SEARCH_ENGINE_COLLECTION_NAME }}
            export DATA_FILE=${{ secrets.DATA_FILE }}

            echo "Run docker compose..."
            make run

            echo "Deployment finished ✅"